dependencies:
  - aave/protocol-v2@1.0.1
  - smartcontractkit/chainlink@1.1.0
compiler:
  solc:
    remappings:
      - '@aave=aave/protocol-v2@1.0.1'
      - '@chainlink=smartcontractkit/chainlink@1.1.0'
networks:
  mainnet-fork: 
    weth_token: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
    lending_pool_addresses_provider: '0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5'
    dai_eth_price_feed: '0x773616e4d11a78f511299002da57a0a94577f1f4'
  rinkeby: 
    weth_token: '0xc778417e063141139fce010982780140aa0cd5ab'
  kovan:
    weth_token: '0xA61ca04DF33B72b235a8A28CfB535bb7A5271B70'
    lending_pool_addresses_provider: '0x88757f2f99175387aB4C6a4b3067c77A695b0349'
    dai_eth_price_feed: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'    
wallets:
  from-key: ${PRIVATE_KEY}
dotenv: .env
wallets: 
  from_key: ${PRIVATE_KEY1}       
